name: CI/CD
on:
  push:
    branches:
    - publish
    # paths:
    # - "src/**.md"
    # - "book.toml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: ./.github/actions/build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: izmrui2020/izmrui2020.github.io/
        publish_branch: main
        publish_dir: ./book
        destination_dir: ./my-knowledge-book
        keep_files: true
