name: CI/CD
on:
  push:
    branches:
    - publish
    paths:
    - "src/**.md"
    - "book.toml"


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: ./.github/actions/build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      
      env:
        EXTERNAL_REPOSITORY: izmrui2020/my-knowledge-book
        PUBLISH_BRANCH: main
        PUBLISH_DIR: ./book
        destination_dir: ./docs
        keep_files: true

